{% set name = "draco" %}
{% set version = "1.5.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/google/draco/archive/{{ version }}.tar.gz
  sha256: 6b7994150bbc513abcdbe22ad778d6b2df10fc8cdc7035e916985b2a209ab826

build:
  number: 0
  skip: true  # [win and vc<14]

requirements:
  build:
    - cmake
    - make
    - {{ compiler('cxx') }}

test:
  commands:
    - draco_encoder -h

about:
  home: https://github.com/google/draco/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: A library for compressing and decompressing 3D geometric meshes and point clouds
  description: |
    A library for compressing and decompressing 3D geometric meshes and point clouds
  doc_url: https://google.github.io/draco/
  dev_url: https://github.com/google/draco

extra:
  recipe-maintainers:
    - hobu
    - chambbj
