travis:
  secure:
    BINSTAR_TOKEN: h0wgmob2atG3j+OfDVdf2aR4ocR6YRDFVhtVK9r4PK2DSmYBWF1z8M3BG7CqMDjk3gGgVRxQJ/ZUbZMCvZlhL4eKZmLarc9Ic+/Lu9QealghIxtBXdsj/6Yk5p81KlaNLnR2vlwy01m2FYxQrRUuXedZfWYKiRipexvazDxp0IT715SbIn95BJ0aeXg/cWZeejUDJyyHWp74MCSjvqpvFleXBc38EF20SjbGVlQaE/Xdn9LT5pFH5fh26OrwlB1Y8+RFuujxaiTxgyELrX/CXLWgdEOHG+Ah10/9oc1iqYaAaFAjCp9nRC6cus1dqqPYgDJCQVfFHbHmz48dMPn8B1GtDG8lBovmeAb4V9+zITGNm5YWpXmALZjKqhrZdFYdY6O9zW1mzCkSRL4gRooBCj8j+tnD4hFUrIJSty37XDAVD+zoOB2lpnEgYu4eWuT9IbiyT0Ym1Mk4PTfeXUBZXYG/17lQOSrJt0cstafIgF8DnAt4V6+vrYX4MmxAgazRBNK/kJMkUVMzjthKaLwVVFotk71R0DM3sFdTXIhRzZg62Q+B9KAuCELhqf0ZefFY2Ys7yu4inITBR9kfy7Hp2qcIkKpwUxEJUu1RELOeUl0/rwk5v6iaAyJenO6eJrqCPM6r3izUUJsFYa2Bmj4FDX0yiQG1/5cUjvAXaLiIwgA=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
